apiVersion: v1
kind: ServiceAccount
metadata:
  name: closet-api
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: closet-api
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "patch", "update"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "patch", "update"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: closet-api
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: closet-api
subjects:
  - kind: ServiceAccount
    name: closet-api
