{{- $existing := (lookup "v1" "Secret" .Release.Namespace "closet-secrets") }}
{{- $keys := list "RANCHER_BOOTSTRAP_PASSWORD" "RANCHER_USER1_PASSWORD" "RANCHER_USER2_PASSWORD" "RANCHER_USER3_PASSWORD" "KEYCLOAK_ADMIN_PASSWORD" "KEYCLOAK_CLIENT_SECRET" "OPENLDAP_ADMIN_PASSWORD" }}
apiVersion: v1
kind: Secret
metadata:
  name: closet-secrets
type: Opaque
data:
{{- range $k := $keys }}
  {{- if and $existing (hasKey $existing.data $k) }}
  {{ $k }}: {{ index $existing.data $k }}
  {{- else }}
  {{ $k }}: {{ randAlphaNum 15 | b64enc }}
  {{- end }}
{{- end }}
