// AUTO-GENERATED by scripts/gen-credentials.mjs from workspace/sidecars/**. Do not edit by hand.
export interface CredentialUsage { sidecar: string; usage: string; }
export interface CredentialField { key: string; label: string; usages: CredentialUsage[]; }
export interface CredentialGroup { name: string; description: string; fields: CredentialField[]; }

export const CREDENTIAL_GROUPS: CredentialGroup[] = [
  {
    "name": "GitHub",
    "description": "Authenticates git operations in the workspace (private repos, higher rate limits).",
    "fields": [
      {
        "key": "ghToken",
        "label": "GitHub token",
        "usages": [
          {
            "sidecar": "workspace",
            "usage": "clones private rancher/dashboard PRs & repos"
          }
        ]
      }
    ]
  },
  {
    "name": "Figma",
    "description": "Access token for the Figma MCP server, so agents can read designs.",
    "fields": [
      {
        "key": "apiKey",
        "label": "Figma API key",
        "usages": [
          {
            "sidecar": "figma",
            "usage": "Figma MCP server authentication"
          }
        ]
      }
    ]
  },
  {
    "name": "Application Collection",
    "description": "SUSE Application Collection login, used to add its chart repo in Rancher.",
    "fields": [
      {
        "key": "appcoEmail",
        "label": "AppCo email",
        "usages": [
          {
            "sidecar": "rancher-browser",
            "usage": "command menu: log in to the SUSE Application Collection chart repo"
          }
        ]
      },
      {
        "key": "appcoToken",
        "label": "AppCo token",
        "usages": [
          {
            "sidecar": "rancher-browser",
            "usage": "command menu: log in to the SUSE Application Collection chart repo"
          }
        ]
      }
    ]
  },
  {
    "name": "AWS",
    "description": "Credentials for provisioning AWS clusters (EC2 nodes / EKS) from the browser command menu.",
    "fields": [
      {
        "key": "awsAccessKey",
        "label": "AWS access key",
        "usages": [
          {
            "sidecar": "rancher-browser",
            "usage": "command menu: EC2/EKS cluster creation"
          }
        ]
      },
      {
        "key": "awsSecretKey",
        "label": "AWS secret key",
        "usages": [
          {
            "sidecar": "rancher-browser",
            "usage": "command menu: EC2/EKS cluster creation"
          }
        ]
      }
    ]
  },
  {
    "name": "Azure",
    "description": "Service-principal credentials for provisioning AKS clusters from the browser command menu.",
    "fields": [
      {
        "key": "azureClientId",
        "label": "Azure client ID",
        "usages": [
          {
            "sidecar": "rancher-browser",
            "usage": "command menu: AKS cluster creation"
          }
        ]
      },
      {
        "key": "azureClientSecret",
        "label": "Azure client secret",
        "usages": [
          {
            "sidecar": "rancher-browser",
            "usage": "command menu: AKS cluster creation"
          }
        ]
      },
      {
        "key": "azureSubscriptionId",
        "label": "Azure subscription ID",
        "usages": [
          {
            "sidecar": "rancher-browser",
            "usage": "command menu: AKS cluster creation"
          }
        ]
      },
      {
        "key": "azureTenantId",
        "label": "Azure tenant ID",
        "usages": [
          {
            "sidecar": "rancher-browser",
            "usage": "command menu: AKS cluster creation"
          }
        ]
      }
    ]
  },
  {
    "name": "GCP",
    "description": "Service-account key for provisioning GKE clusters from the browser command menu.",
    "fields": [
      {
        "key": "gcpServiceAccountKey",
        "label": "GCP service account key",
        "usages": [
          {
            "sidecar": "rancher-browser",
            "usage": "command menu: GKE cluster creation"
          }
        ]
      }
    ]
  }
];

// Flat list of every credential key (for the "N/total" Keys column).
export const CREDENTIAL_KEYS: string[] = ["ghToken","apiKey","appcoEmail","appcoToken","awsAccessKey","awsSecretKey","azureClientId","azureClientSecret","azureSubscriptionId","azureTenantId","gcpServiceAccountKey"];
